### ISSUE TITLE
Website is offline?

### ISSUE THREAD

**Issue by OliverJAsh** [afeld/jsonp#63]
https://jsonp.afeld.me/?url=https%3A%2F%2Fwww.google.co.uk%2F%3Fgfe_rd%3Dcr%26ei%3DOSemVafTD4Pj8wfe0IDYBQ%26gws_rd%3Dssl

![image](https://cloud.githubusercontent.com/assets/921609/8695260/fac743f8-2adb-11e5-9912-7225d8f915ab.png)

**Comment by afeld** [comment]
It's failing because the response isn't JSON, which I just realized [the proxy shouldn't have to worry about](https://github.com/afeld/jsonp/issues/65) anyway. Works with adding `raw=true`.

https://jsonp.afeld.me/?raw=true&url=https%3A%2F%2Fwww.google.co.uk%2F%3Fgfe_rd%3Dcr%26ei%3DOSemVafTD4Pj8wfe0IDYBQ%26gws_rd%3Dssl
